<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>es.unican.is2</groupId>
    <artifactId>SegurosFinal</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>
    <name>SegurosFinal</name>
    
    <!-- Este es el nombre por defecto en Sonar -->
    <properties>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.source>21</maven.compiler.source>
        <!-- Propiedades para usar SonarQube en local-->
        <sonar.host.url>http://localhost:9000</sonar.host.url>
        <!-- modificar este token por el vuestro -->
        <sonar.token>sqa_6b08712d064416dc1345749c52f4388abf6a1567</sonar.token>
        <!-- Propiedades para usar SonarCloud -->
        <!-- <sonar.projectKey>Seguros3</sonar.projectKey> -->
        <!-- <sonar.projectName>Seguros3</sonar.projectName> -->
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
    </properties>
    
    <!--
     Nombres de los directorios que contienen los módulos. Asegurar que se correspondan con vuestros directorios 
    -->
    <modules>
        <module>SegurosCommon</module>
        <module>SegurosDAO</module>
        <module>SegurosBusiness</module>
        <module>SegurosGUI</module>
        <module>SegurosMain</module>
    </modules>
    
    <build>
        <plugins>
            <!-- Maven Surefire Plugin para ejecutar pruebas unitarias -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M9</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                </configuration>
            </plugin>
            
            <!-- JaCoCo Maven Plugin para cobertura de código (EclEmma) -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
